INSERT INTO produtos (nome, descricao, preco, categoria, estoque) VALUES
('Arroz Tipo 1 5kg', 'Arroz branco tipo 1, grãos longos e soltos. Pacote de 5 kg, rendimento alto no cozimento.', 24.90, 'Mercearia', 80),
('Feijão Carioca 1kg', 'Feijão carioca selecionado, grãos uniformes. Pacote de 1 kg.', 8.49, 'Mercearia', 65),
('Açúcar Cristal 1kg', 'Açúcar cristal refinado para uso diário. Pacote de 1 kg.', 4.79, 'Mercearia', 120),
('Óleo de Soja 900ml', 'Óleo de soja refinado, garrafa de 900 ml. Ideal para frituras e refogados.', 6.99, 'Mercearia', 90),
('Macarrão Espaguete 500g', 'Massa de sêmola de trigo durum, pacote de 500 g. Cozimento em cerca de 8 minutos.', 4.29, 'Mercearia', 70),
('Leite Integral 1L', 'Leite UHT integral, caixa de 1 litro. Fonte de cálcio e proteínas.', 5.49, 'Laticínios', 110),
('Leite Desnatado 1L', 'Leite UHT desnatado, caixa de 1 litro. Menor teor de gordura.', 5.29, 'Laticínios', 45),
('Queijo Mussarela 400g', 'Queijo mussarela fatiado, peça de 400 g. Ideal para lanches e pizzas.', 22.90, 'Laticínios', 28),
('Iogurte Natural 170g', 'Iogurte natural integral, pote de 170 g. Sem adição de açúcar.', 3.49, 'Laticínios', 54),
('Manteiga com Sal 200g', 'Manteiga extra com sal, tablete de 200 g.', 12.90, 'Laticínios', 36),
('Refrigerante Cola 2L', 'Refrigerante sabor cola, garrafa PET de 2 litros. Servir gelado.', 9.99, 'Bebidas', 95),
('Refrigerante Guaraná 2L', 'Refrigerante de guaraná, garrafa PET de 2 litros.', 8.49, 'Bebidas', 72),
('Suco de Laranja 1L', 'Suco de laranja integral, caixa de 1 litro. Sem adição de açúcar.', 11.90, 'Bebidas', 40),
('Água Mineral 1,5L', 'Água mineral sem gás, garrafa de 1,5 litro.', 2.49, 'Bebidas', 200),
('Café Torrado e Moído 500g', 'Café torrado e moído, pacote a vácuo de 500 g. Torra média.', 18.90, 'Bebidas', 50),
('Detergente Neutro 500ml', 'Detergente líquido neutro para louças, frasco de 500 ml.', 2.99, 'Limpeza', 88),
('Sabão em Pó 1,6kg', 'Sabão em pó concentrado para roupas, caixa de 1,6 kg.', 19.90, 'Limpeza', 42),
('Papel Higiênico 12 rolos', 'Papel higiênico folha dupla, fardo com 12 rolos de 30 m.', 16.90, 'Limpeza', 33),
('Banana Prata kg', 'Banana prata madura, vendida por quilograma. Doce e ideal para vitaminas.', 6.99, 'Hortifruti', 25),
('Tomate kg', 'Tomate salada fresco, vendido por quilograma.', 7.49, 'Hortifruti', 18),
('Alface Crespa un', 'Alface crespa hidropônica, unidade. Folhas crocantes.', 3.99, 'Hortifruti', 22),
('Pão Francês kg', 'Pão francês fresco do dia, vendido por quilograma. Crocante por fora e macio por dentro.', 14.90, 'Padaria', 15),
('Pão de Forma 500g', 'Pão de forma tradicional, pacote de 500 g. 12 fatias.', 8.49, 'Padaria', 30),
('Peito de Frango kg', 'Peito de frango resfriado, vendido por quilograma. Sem osso e sem pele.', 21.90, 'Açougue', 12),
('Carne Moída kg', 'Carne bovina moída de primeira, vendida por quilograma.', 32.90, 'Açougue', 8),
('Água Sanitária 1L', 'Água sanitária para desinfecção, frasco de 1 litro. Produto temporariamente esgotado.', 4.19, 'Limpeza', 0);
